version: "3.7"

services:
  blog-app-frontend-http:
    build:
      context: .
      dockerfile: docker/app-frontend-http/Dockerfile
    volumes:
      - ./app/assets/:/var/www/html/public/assets/
    links:
      - blog-app-frontend-php

  blog-app-frontend-php:
    build:
      context: .
      dockerfile: docker/app-frontend-php/Dockerfile
    volumes:
      - ./app/:/var/www/html/
    environment:
      APP_ENV: dev
      RDS_HOSTNAME: db
      RDS_PORT: 5432
      RDS_DB_NAME: example
      RDS_PASSWORD: example
      RDS_USERNAME: example
    user: 1000:1000
    links:
      - db

  blog-app-db-migrations:
    build:
      context: .
      dockerfile: docker/app-frontend-php/Dockerfile
    command: ["/var/www/html/bin/migrate"]
    volumes:
      - ./app/:/var/www/html/
    environment:
      APP_ENV: dev
      RDS_HOSTNAME: db
      RDS_PORT: 5432
      RDS_DB_NAME: example
      RDS_PASSWORD: example
      RDS_USERNAME: example
    user: 1000:1000
    links:
      - db
    restart: "no"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - pgdata-example:/var/lib/postgresql/data

volumes:
  pgdata-example: ~
