version: "3.7"

services:
  blog-app-frontend-http:
    build:
      context: .
      dockerfile: docker/app-frontend-http/Dockerfile
    volumes:
      - ./app/assets/:/var/www/html/public/assets/
    links:
      - blog-app-frontend-php

  blog-app-frontend-php:
    build:
      context: .
      dockerfile: docker/app-frontend-php/Dockerfile
    volumes:
      - ./app/:/var/www/html/
    environment:
      APP_ENV: dev
    user: 1000:1000
