imprint:
  path: /imprint
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowImprintController::action

post:
  path: /{slug}
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowPostController::action

posts:
  path: /
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowPostsController::action
