index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /posts
    permanent: true

posts:
  path: /posts
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowPostsController::action

post:
  path: /posts/{slug}
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowPostController::action

imprint-en:
  path: /imprint
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowImprintEnController::action

imprint-de:
  path: /impressum
  controller: Mhert\Blog\Infrastructure\Controllers\Frontpage\ShowImprintDeController::action
