# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        public: false

    Aws\DynamoDb\DynamoDbClient:
        arguments:
            $args:
                endpoint: 'http://db:8000'
                region: 'us-west-2'
                version: 'latest'
                credentials:
                    key: 'fakeMyKeyId'
                    secret: 'fakeMyKeyId'

    Mhert\Blog\Infrastructure\DynamoDb\PostTableName:
        arguments:
            $ebAppEnv: '%env(EB_APP_ENV)%'

    Mhert\Blog\Domain\Frontpage\Post\PostRepository: '@Mhert\Blog\Infrastructure\DynamoDb\Frontpage\Post\DynamoDbPostRepository'

    #Mhert\Blog\Infrastructure\MarkdownParser\MarkdownParser: '@Mhert\Blog\Infrastructure\MarkdownParser\MichelfParsedown\MichelfParsedownMarkdownParser'
    Mhert\Blog\Infrastructure\MarkdownParser\MarkdownParser: '@Mhert\Blog\Infrastructure\MarkdownParser\Parsedown\ParsedownMarkdownParser'

    Mhert\Blog\:
        resource: '../src/Mhert/Blog/*'
        exclude:
            - '../src/Mhert/Blog/Infrastructure/DynamoDb/PostTableName.php'

    Mhert\Blog\Infrastructure\Controllers\:
        resource: '../src/Mhert/Blog/Infrastructure/Controllers'
        tags: ['controller.service_arguments']

    Mhert\Blog\Infrastructure\Commands\:
        resource: '../src/Mhert/Blog/Infrastructure/Commands'
        tags: ['console.command']

    Parsedown:
        class: Parsedown
